#server:
#  port: 8083
#
spring:
  application:
    name: jml-cloud-suppliers-serverless-service
#  thymeleaf:
#    enabled: false
#  main:
#    banner-mode: "console"
#
application:
  version: "@project.version@"

logging:
#  file:
#    name: logs/${spring.application.name}.log
  config: classpath:log4j2-spring.xml
#  level:
#    org.springframework: DEBUG

#  datasource:
#    url: jdbc:mysql://localhost:3306/application_table_db
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  security:
#    user:
#      name: admin
#      password: admin
#
#jwt:
#  secret: gOOKoiLpQ/XDAAo9I85L/2Bh3Y9KWvDFyRf7vqqGP38=
#  expiration: 3600000  # 1 hora en milisegundos
#  refreshExpirationMs: 14400000  # 3 horas en milisegundos
